version: '3'
services:
  enshrouded:
    image: sknnr/enshrouded-dedicated-server:latest
    container_name: enshrouded
    ports:
      - "15636:15636/udp"
      - "15637:15637/udp"
    environment:
#      - SERVER_NAME=Enshrouded Containerized
      - SERVER_PASSWORD=groovyfunky
#      - GAME_PORT=15636
#      - QUERY_PORT=15637
      - SERVER_SLOTS=4
#      - SERVER_IP=35.212.241.134
    volumes:
      - enshrouded-persistent-data:/home/steam/enshrouded/savegame

volumes:
  enshrouded-persistent-data:
